# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# 英文菜单
[[main]]
identifier = "archives"
name = "Archives"
url = "/en/archives/"
weight = 2
[main.params]
icon = "archives"

[[main]]
identifier = "search"
name = "Search"
url = "/en/search/"
weight = 3
[main.params]
icon = "search"

[[main]]
identifier = "links"
name = "Links"
url = "/en/links/"
weight = 4
[main.params]
icon = "link"

# 中文菜单
[[main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 2
[main.params]
icon = "archives"

[[main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 3
[main.params]
icon = "search"

[[main]]
identifier = "links"
name = "链接"
url = "/links/"
weight = 4
[main.params]
icon = "link"



[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CaiJimmy/hugo-theme-stack"

[social.params]
icon = "brand-github"

